### ISSUE TITLE
AMASS dataset transform

### ISSUE THREAD

**Issue by RHnejad** [jsun57/CoMusion#1]
Hello, 

Thanks for sharing your work. 

While running the amass code I get an error regarding the .flip_prob in the transform function.  I managed to run the code by disabling transform at (_get_hash_str) but I was wondering whether the DataAugmentation is not complete in the code.

Thanks :)

**Comment by jsun57** [comment]
Hi, I have cleaned up the code for amass data script. Only rotation is used as data augmentation.
